### ISSUE TITLE
Service Bus

### ISSUE THREAD

**Issue by rryk** [fives-team/FiVES#31]
Torsten has suggested to apply a concept of Service Oriented Architecture to the FIVES. We've discussed this and came up with the following idea. Service Bus will be introduced and serve as an additional layer between the ECA-model and plugins that will processing changes to the world. Any plugin wishing to make a change will need to send that change to the Service Bus, which may decide either to write it to the model or to redirect it to another plugin. For example, this can be used to redirect an update to `position` from the Motion plugin to the Physics plugin to ensure that positions written to the world are valid. Physics plugin may decide to write update as is or to discard it and publish another update (which places the object at the position of some collision).

System Bus will use a configuration file to make it's decisions, which may require it to ignore the update, to redirect it to another plugin (or maybe even replicate it to several plugins) or to write it to the model. Plugins in turn will only receive events from the Service Bus, not from the model, which may simplify model implementation (no events).

This idea may also be extended to solve issue #29. However, should the service bus be extended to the level of synchronization network, FiVES may become too complicated to be used as a server for simple networking game.

**Comment by tospie** [comment]
Service Bus implementation part of FiVES since https://github.com/fives-team/FiVES/commit/5ba731726732c6c4815dd80b452d298befa01640
