### ISSUE TITLE
Manual test 2 with both plugins loaded is failing

### ISSUE THREAD

**Issue by rryk** [fives-team/FiVES#36]
The direction is not preserved. Also rotation control in the reloaded clients after server restart behaves strangely. In particular when smoothly rotating around (just hold A or D key) the direction sometimes changes suddenly. This seems to be a regression, but since Persistence was broken for a while I am not sure when it happened.

**Comment by tospie** [comment]
This bug was related to old persistence plugin which will be re-written in https://github.com/fives-team/FiVES/issues/30
